CREATE DATABASE bdLoja2DS
USE bdLoja2DS

CREATE TRIGGER tgInsertMsg
	ON tbCaixa
	FOR INSERT
	AS
BEGIN
	PRINT ('você está inserindo na tabela caixa')
END

CREATE TABLE tbCAIXA
(
	CODIGO INT PRIMARY KEY IDENTITY(1,1),
	DATA DATETIME,
	SALDO_INICIAL DECIMAL(10,2),
	SALDO_FINAL DECIMAL(10,2)
);

INSERT INTO tbCAIXA
VALUES (CONVERT(DATETIME, CONVERT(VARCHAR, GETDATE(), 103)), 100, 100)

GO
CREATE TABLE tbVENDAS
(
	DATAVENDA DATETIME,
	CODIGO INT,
	VALOR DECIMAL(10,2)
);

CREATE TRIGGER tgAtualizaCaixa ON tbVENDAS
	AFTER INSERT
	AS
		BEGIN
			DECLARE @valorVenda	DECIMAL (10,2)
			DECLARE @data	DATETIME
			SET	@valorVenda = (SELECT VALOR FROM inserted)
			SET	@data = (SELECT CONVERT(VARCHAR(12), DATAVENDA, 103)FROM inserted)
			UPDATE tbCAIXA
				SET SALDO_FINAL = SALDO_FINAL + @valorVenda
				WHERE DATA = @data
			PRINT('O saldo final do Caixa foi atualizado na data '+CONVERT(VARCHAR(12),@data,103))
		END

INSERT INTO tbVENDAS (DATAVENDA,CODIGO,VALOR)
VALUES 
('25/09/2026',1,670.67);

